[graph]
all-features = true
exclude-dev = true

[bans]
multiple-versions = "allow"

# Not exhaustive, just whitelist the current dependency tree
[licenses]
allow = [
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-3-Clause",
  "LGPL-3.0-only",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
